on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'      
      - name: Install dependencies
        run: yarn install --frozen-lockfile 
      - name: Run tests
        run: |
          npx playwright install-deps
          npx playwright install-deps chromium
          yarn test
